### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by josunyjostar** [codestates/lolinfo#3]
## 1. 시스템 아키텍처 
- [ ]  JWT를 이용한 로그인 구현 | 필수 | 프론트엔드, 백엔드 | ★
- [ ]  권한 부여(Authorization)에 따른 기능의 접근 제한 구현 (예- 일반 사용자, 관리자 권한) | 필수 | 프론트엔드, 백엔드 | ★
- [ ] OAuth 2.0을 이용한 소셜 로그인 | 권장 | 프론트엔드, 백엔드 | ★

## 2. UI/UX
- [ ]  회원가입, 로그인 및 회원정보 수정 시 유효성 검사 | 필수 | 프론트엔드 | ★
- [ ]  소셜 로그인 외 서비스 자체 회원가입 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  회원가입 없이 '체험하기' 형식으로 가볍게 기능을 이용할 수 있는 장치 마련 | 필수 | 프론트엔드 | ★
- [ ]  마이페이지를 통해 사용자 개인정보 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  (소셜 로그인이 아닐 경우) 비밀번호 수정 기능 제공 | 필수 | 프론트엔드 | ★
- [ ]  라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다룬 것: 탭, 드랍다운, 모달 등) | 필수 | 프론트엔드 | ★
- [ ]  라이브러리를 사용하지 않고 React 컴포넌트 직접 작성 (유어클래스에서 다루지 않은 것) | 권장 | 프론트엔드 | ★★★
- [ ]  회원 탈퇴나 리소스 삭제시 확인(confirm) 모달 제공 | 권장 | 프론트엔드 | ★
- [ ]  검색 필터링 기능 | 권장 | 프론트엔드, 백엔드 | ★★★
- [ ]  데이터를 API로 받아 와서 리스트 구현 | 권장 | 프론트엔드 | ★★
- [ ]  3rd-party API 호출 | 권장 | 프론트엔드 | ★
- [ ]  모바일 환경 대응 및 반응형 웹 | 권장 | 프론트엔드 | ★★

## 3. 스키마 및 API
1. [ ] N:M (다대다) 관계 설정 | 필수 | 백엔드 | ★
2. [x] ERD (DB Diagram) 작성 | 필수 | 백엔드 | ★
3. [ ] API 작성 툴 (Swagger, Postman, Gitbook API) 을 사용하여 요청/응답 및 JSON 키/값 형식 기술 | 필수 | 백엔드 | ★★
4. [ ] ORM 사용 (sequelize, typeorm 권장) | 권장 | 백엔드 | ★
5. [ ] 페이지네이션 구현 | 권장 | 백엔드 | ★★★

## 4. DevOps
1. [x] [릴리즈] 깃허브 커밋메세지 규칙 합의 | 필수 | 프론트엔드, 백엔드 | ★
2. [x] [코드] 버전 규칙 합의 | 필수 | 프론트엔드, 백엔드 | ★
3. [x] [릴리즈] PR 형식 합의 | 권장 | 프론트엔드, 백엔드 | ★
4. [x] [배포] 배포 자동화 설정 | 권장 | 백엔드 | ★
5. [x] [배포] 도메인 구매 및 HTTPS 배포 | 권장 | 백엔드 | ★★★
6. [ ] [테스트] 백엔드 테스트 코드 작성 | 권장 | 백엔드 | ★★★
7. [x]  S3로 파일 업로드 | 권장 | 프론트엔드, 백엔드 | ★★★
## Advanced (도전)
1. [ ] 무한 스크롤 | 도전 | 프론트엔드 | ★★★
2. [ ] reCAPTCHA 사용 | 도전 | 프론트엔드 | ★★
3. [ ] 스크롤에 의한 애니메이션 적용 (greensock 사용 권장) | 도전 | 프론트엔드 | ★★★

## Nightmare (신중)
1. [ ] Socket.io를 이용한 채팅 기능 | 도전 | 프론트엔드, 백엔드 | ★★★★
2. [x] d3를 이용한 시각화 | 도전 | 프론트엔드 | ★★★★
3. [ ] Canvas, SVG를 활용한 동적인 이미지 표시 | 도전 | 프론트엔드 | ★★★★★
