### ISSUE TITLE
[Task] wiki 작성

### ISSUE THREAD

**Issue by josunyjostar** [codestates/lolinfo#6]
### ISSUE
 * Group:  `sr`
 * Type: `feature`
 
### TODO
 1. [x]  wiki 레이아웃 작성
 2. [x]  이슈 템플릿 및 이유 작성
 3. [x]  Todo List 작성
 ### Estimated time

* Estimated time: `4h`
* Group : `sr`
* Urgency: `Low`
